/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.
 */

plugins {
    java
    // antlr and protobuf plugins disabled - using Maven pre-generated sources
    // antlr
    // id("com.google.protobuf") version "0.9.4"
}

@Suppress("UNCHECKED_CAST")
val versions = rootProject.extra["versions"] as Map<String, String>
val dorisHome = rootProject.extra["dorisHome"] as String
val dorisThirdparty = rootProject.extra["dorisThirdparty"] as String

// ============ Source Sets ============
sourceSets {
    main {
        java {
            srcDirs(
                "src/main/java",
                "$dorisHome/gensrc/build/gen_java",  // Thrift generated
                "target/generated-sources/antlr4",
                "target/generated-sources/jflex",
                "target/generated-sources/cup",
                "target/generated-sources/annotations",
                "target/generated-sources/build",
                "target/generated-sources/org",      // Proto generated
                "target/generated-sources/doris",    // Additional proto
                "target/generated-sources/protobuf/java",
                "target/generated-sources/protobuf/grpc-java"
            )
        }
        resources {
            srcDirs("src/main/resources")
        }
    }
}

// ============ Dependencies ============
dependencies {
    // Project dependency
    implementation(project(":fe-common"))

    // ============ ANTLR (runtime only, sources pre-generated by Maven) ============
    implementation("org.antlr:antlr4-runtime:${versions["antlr4"]}")

    // ============ Parser generators ============
    implementation("de.jflex:jflex:${versions["jflex"]}")
    // Only need java-cup-runtime for compiled code, not java-cup generator
    implementation("net.sourceforge.czt.dev:java-cup-runtime:0.11-a-czt01-cdh")

    // ============ Core ============
    implementation("com.google.guava:guava:${versions["guava"]}")
    implementation("com.google.code.gson:gson:${versions["gson"]}")
    implementation("com.google.protobuf:protobuf-java:${versions["protobuf"]}")
    implementation("com.squareup:protoparser:3.1.5")

    // ============ Jackson ============
    implementation("com.fasterxml.jackson.core:jackson-core:${versions["jackson"]}")
    implementation("com.fasterxml.jackson.core:jackson-databind:${versions["jackson"]}")
    implementation("com.fasterxml.jackson.core:jackson-annotations:${versions["jackson"]}")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${versions["jackson"]}")
    implementation("com.fasterxml.jackson.module:jackson-module-jaxb-annotations:${versions["jackson"]}")

    // ============ gRPC ============
    implementation("io.grpc:grpc-netty:${versions["grpc"]}")
    implementation("io.grpc:grpc-protobuf:${versions["grpc"]}")
    implementation("io.grpc:grpc-stub:${versions["grpc"]}")
    implementation("io.grpc:grpc-core:${versions["grpc"]}")

    // ============ Thrift ============
    implementation("org.apache.thrift:libthrift:${versions["thrift"]}")

    // ============ Netty ============
    implementation("io.netty:netty-all:${versions["netty"]}")

    // ============ Logging ============
    implementation("org.apache.logging.log4j:log4j-core:${versions["log4j"]}")
    implementation("org.apache.logging.log4j:log4j-api:${versions["log4j"]}")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:${versions["log4j"]}")
    implementation("org.apache.logging.log4j:log4j-iostreams:${versions["log4j"]}")
    implementation("org.slf4j:slf4j-api:${versions["slf4j"]}")
    implementation("com.lmax:disruptor:3.4.4")

    // ============ Spring Boot ============
    implementation("org.springframework.boot:spring-boot-starter:${versions["spring"]}") {
        exclude(group = "ch.qos.logback", module = "logback-classic")
        exclude(group = "org.apache.logging.log4j", module = "log4j-to-slf4j")
    }
    implementation("org.springframework.boot:spring-boot-devtools:${versions["spring"]}")
    implementation("org.springframework.boot:spring-boot-starter-data-ldap:${versions["spring"]}")
    implementation("org.springframework.boot:spring-boot-starter-web:${versions["spring"]}") {
        exclude(group = "org.springframework.boot", module = "spring-boot-starter-tomcat")
        exclude(group = "ch.qos.logback", module = "logback-classic")
    }
    implementation("org.springframework.boot:spring-boot-starter-jetty:${versions["spring"]}")

    // ============ Commons ============
    implementation("commons-io:commons-io:${versions["commonsIo"]}")
    implementation("org.apache.commons:commons-lang3:${versions["commonsLang3"]}")
    implementation("commons-lang:commons-lang:${versions["commonsLang"]}")
    implementation("commons-codec:commons-codec:${versions["commonsCodec"]}")
    implementation("commons-cli:commons-cli:${versions["commonsCli"]}")
    implementation("commons-pool:commons-pool:${versions["commonsPool"]}")
    implementation("org.apache.commons:commons-pool2:${versions["commonsPool2"]}")
    implementation("org.apache.commons:commons-text:${versions["commonsText"]}")
    implementation("commons-validator:commons-validator:${versions["commonsValidator"]}")
    implementation("commons-beanutils:commons-beanutils:${versions["commonsBeanutils"]}")
    implementation("org.apache.commons:commons-configuration2:${versions["commonsConfiguration2"]}")
    implementation("org.apache.commons:commons-compress:${versions["commonsCompress"]}")
    implementation("commons-collections:commons-collections:${versions["commonsCollections"]}")
    implementation("commons-fileupload:commons-fileupload:1.5")

    // ============ HTTP ============
    implementation("org.apache.httpcomponents:httpclient:${versions["httpclient"]}")
    implementation("org.apache.httpcomponents:httpcore:${versions["httpcore"]}")

    // ============ Hadoop ============
    compileOnly("org.apache.hadoop:hadoop-common:${versions["hadoop"]}") {
        exclude(group = "org.slf4j", module = "slf4j-reload4j")
    }
    compileOnly("org.apache.hadoop:hadoop-hdfs:${versions["hadoop"]}")
    compileOnly("org.apache.hadoop:hadoop-hdfs-client:${versions["hadoop"]}")
    compileOnly("org.apache.hadoop:hadoop-client:${versions["hadoop"]}")
    compileOnly("org.apache.hadoop:hadoop-auth:${versions["hadoop"]}")

    // ============ HBase ============
    implementation("org.apache.hbase:hbase-client:${versions["hbase"]}") {
        exclude(group = "org.apache.hadoop", module = "hadoop-yarn-api")
        exclude(group = "org.apache.hadoop", module = "hadoop-yarn-common")
    }
    implementation("org.apache.hbase:hbase-server:${versions["hbase"]}") {
        exclude(group = "org.apache.hadoop", module = "hadoop-yarn-api")
        exclude(group = "org.apache.hadoop", module = "hadoop-yarn-common")
    }
    implementation("org.apache.hbase:hbase-common:${versions["hbase"]}")

    // ============ Zookeeper ============
    implementation("org.apache.zookeeper:zookeeper:${versions["zookeeper"]}") {
        exclude(group = "ch.qos.logback", module = "*")
    }

    // ============ Data Formats ============
    implementation("org.apache.avro:avro:${versions["avro"]}")
    implementation("org.apache.parquet:parquet-hadoop:${versions["parquet"]}")
    implementation("org.apache.orc:orc-core:${versions["orc"]}")

    // ============ Iceberg ============
    implementation("org.apache.iceberg:iceberg-core:${versions["iceberg"]}")
    implementation("org.apache.iceberg:iceberg-api:${versions["iceberg"]}")
    implementation("org.apache.iceberg:iceberg-data:${versions["iceberg"]}")
    implementation("org.apache.iceberg:iceberg-common:${versions["iceberg"]}")

    // ============ Arrow ============
    implementation("org.apache.arrow:arrow-vector:${versions["arrow"]}:shade-format-flatbuffers")
    implementation("org.apache.arrow:arrow-memory-netty:${versions["arrow"]}")
    implementation("org.apache.arrow:flight-core:${versions["arrow"]}")
    implementation("org.apache.arrow:flight-sql:${versions["arrow"]}")
    implementation("org.apache.arrow:arrow-jdbc:${versions["arrow"]}")

    // ============ Paimon ============
    implementation("org.apache.paimon:paimon-core:${versions["paimon"]}")

    // ============ Hudi ============
    implementation("org.apache.hudi:hudi-common:1.0.2")
    implementation("org.apache.hudi:hudi-client-common:1.0.2")

    // ============ Kubernetes ============
    implementation("io.fabric8:kubernetes-client:${versions["fabric8"]}")

    // ============ Metrics ============
    implementation("io.dropwizard.metrics:metrics-core:${versions["metricsCore"]}")

    // ============ Database ============
    implementation("com.zaxxer:HikariCP:${versions["hikaricp"]}")

    // ============ Cloud - AWS SDK v1 ============
    implementation("com.amazonaws:aws-java-sdk-s3:${versions["awsJavaSdk"]}")
    implementation("com.amazonaws:aws-java-sdk-sts:${versions["awsJavaSdk"]}")
    implementation("com.amazonaws:aws-java-sdk-glue:${versions["awsJavaSdk"]}")
    implementation("com.amazonaws:aws-java-sdk-core:${versions["awsJavaSdk"]}")
    implementation("com.amazonaws:aws-java-sdk-kms:${versions["awsJavaSdk"]}")
    implementation("com.amazonaws:aws-java-sdk-dynamodb:${versions["awsJavaSdk"]}")

    // ============ Cloud - AWS SDK v2 ============
    implementation("software.amazon.awssdk:s3:2.29.26")
    implementation("software.amazon.awssdk:sts:2.29.26")
    implementation("software.amazon.awssdk:auth:2.29.26")
    implementation("software.amazon.awssdk:regions:2.29.26")
    implementation("software.amazon.awssdk:sdk-core:2.29.26")
    implementation("software.amazon.awssdk:s3-transfer-manager:2.29.26")
    implementation("software.amazon.awssdk:url-connection-client:2.29.26")

    // ============ Aliyun ============
    implementation("com.aliyun:aliyun-java-sdk-core:4.5.25")
    implementation("com.aliyun.oss:aliyun-sdk-oss:3.15.0")
    implementation("com.aliyun.odps:odps-sdk-core:0.49.0-public")
    implementation("com.aliyun.odps:odps-sdk-mapred:0.49.0-public")
    implementation("com.aliyun.odps:odps-sdk-table-api:0.49.0-public")

    // ============ Azure ============
    implementation("com.azure:azure-storage-blob:12.22.0")
    implementation("com.azure:azure-storage-blob-batch:12.22.0")
    implementation("com.azure:azure-storage-common:12.22.0")
    implementation("com.azure:azure-core:1.36.0")
    implementation("com.azure:azure-core-http-netty:1.13.0")
    implementation("com.azure:azure-identity:1.11.0")

    // ============ Huawei Cloud ============
    implementation("com.huaweicloud:esdk-obs-java-bundle:3.24.3")
    implementation("com.huaweicloud.sdk:huaweicloud-sdk-iam:3.1.69")

    // ============ Tencent Cloud ============
    implementation("com.qcloud:cos_api:5.6.89") {
        exclude(group = "com.tencentcloudapi", module = "tencentcloud-sdk-java-kms")
    }

    // ============ Serialization ============
    implementation("org.xerial.snappy:snappy-java:${versions["snappy"]}")
    implementation("com.esotericsoftware:kryo-shaded:${versions["kryo"]}")

    // ============ Misc ============
    implementation("org.objenesis:objenesis:${versions["objenesis"]}")
    implementation("org.javassist:javassist:${versions["javassist"]}")
    implementation("cglib:cglib:${versions["cglib"]}")
    implementation("com.google.re2j:re2j:${versions["re2j"]}")
    implementation("com.googlecode.java-ipv6:java-ipv6:0.17")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    implementation("dk.brics.automaton:automaton:1.11-8")
    implementation("com.github.mifmif:generex:1.0.1")
    implementation("joda-time:joda-time:2.8.1")
    implementation("hu.webarticum:tree-printer:1.2")
    implementation("org.yaml:snakeyaml:${versions["snakeyaml"]}")
    implementation("org.quartz-scheduler:quartz:2.3.2")
    implementation("com.github.oshi:oshi-core:6.4.5")
    implementation("org.apache.velocity:velocity-engine-core:2.4")
    implementation("org.checkerframework:checker:3.43.0")
    implementation("com.nimbusds:nimbus-jose-jwt:10.0.1")

    // ============ Jakarta ============
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:2.3.3")
    implementation("jakarta.activation:jakarta.activation-api:1.2.2")
    implementation("jakarta.annotation:jakarta.annotation-api:2.1.1")

    // ============ Jetty ============
    implementation("org.eclipse.jetty:jetty-server:${versions["jetty"]}")
    implementation("org.eclipse.jetty:jetty-servlet:${versions["jetty"]}")
    implementation("org.eclipse.jetty:jetty-webapp:${versions["jetty"]}")

    // ============ Servlet ============
    implementation("javax.servlet:javax.servlet-api:3.1.0")

    // ============ AspectJ ============
    implementation("org.aspectj:aspectjweaver:${versions["aspectj"]}")
    implementation("org.aspectj:aspectjrt:${versions["aspectj"]}")

    // ============ Lombok ============
    compileOnly("org.projectlombok:lombok:${versions["lombok"]}")
    annotationProcessor("org.projectlombok:lombok:${versions["lombok"]}")

    // ============ Doris Local Dependencies ============
    implementation("org.apache.doris:je:${versions["je"]}")
    compileOnly("org.apache.doris:hive-catalog-shade:${versions["hiveCatalogShade"]}")

    // ============ XNIO ============
    implementation("org.jboss.xnio:xnio-nio:3.8.14.Final")
    implementation("org.jboss.xnio:xnio-api:3.8.14.Final")

    // ============ Awaitility ============
    implementation("org.awaitility:awaitility:4.2.0")

    // ============ Kafka ============
    implementation("org.apache.kafka:kafka-clients:3.4.0")

    // ============ Calcite ============
    implementation("org.apache.calcite:calcite-core:1.33.0")
    implementation("org.apache.calcite.avatica:avatica-core:1.22.0")

    // ============ Ranger ============
    implementation("org.apache.ranger:ranger-plugins-common:2.4.0") {
        exclude(group = "org.slf4j", module = "slf4j-log4j12")
    }

    // ============ FastJSON ============
    implementation("com.alibaba:fastjson:1.2.83")

    // ============ Baidu Cloud ============
    implementation("com.baidubce:bce-java-sdk:0.10.262")

    // ============ Tencent Cloud STS ============
    implementation("com.tencentcloudapi:tencentcloud-sdk-java-sts:3.1.678")

    // ============ Airlift ============
    implementation("io.airlift:units:1.3")
    implementation("io.airlift:slice:0.44")
    implementation("io.airlift:configuration:5")
    implementation("io.airlift:stats:1.7")
    implementation("io.airlift:log:0.3")
    implementation("io.airlift:bootstrap:0.3")
    implementation("io.airlift:json:0.3")
    implementation("io.airlift:concurrent:2")
    implementation("io.airlift:security:1")

    // ============ gRPC Netty Shaded ============
    implementation("io.grpc:grpc-netty-shaded:${versions["grpc"]}")

    // ============ OpenTelemetry ============
    implementation("io.opentelemetry:opentelemetry-api:1.32.0")
    implementation("io.opentelemetry:opentelemetry-sdk:1.32.0")
    implementation("io.opentelemetry:opentelemetry-context:1.32.0")

    // ============ Substrait ============
    implementation("io.substrait:core:0.33.0")

    // ============ Trino ============
    implementation("io.trino:trino-main:${versions["trino"]}") {
        exclude(group = "org.antlr", module = "antlr4-runtime")
        exclude(group = "io.airlift", module = "log")
        exclude(group = "io.airlift", module = "log-manager")
    }
    implementation("io.trino:trino-spi:${versions["trino"]}")
    implementation("io.trino:trino-parser:${versions["trino"]}")
    implementation("io.trino:trino-client:${versions["trino"]}")
    implementation("io.trino:trino-memory-context:${versions["trino"]}")
    implementation("io.trino:trino-array:${versions["trino"]}")
    implementation("io.trino:trino-hive:${versions["trino"]}")
    implementation("io.trino:trino-iceberg:${versions["trino"]}")
    implementation("io.trino:trino-orc:${versions["trino"]}")
    implementation("io.trino:trino-parquet:${versions["trino"]}")
    implementation("io.trino:trino-geospatial-toolkit:${versions["trino"]}")
    implementation("io.trino:trino-plugin-toolkit:${versions["trino"]}")

    // ============ Iceberg AWS ============
    implementation("org.apache.iceberg:iceberg-aws:${versions["iceberg"]}")
    implementation("org.apache.iceberg:iceberg-bundled-guava:${versions["iceberg"]}")

    // ============ Hudi Hadoop ============
    implementation("org.apache.hudi:hudi-hadoop-common:1.0.2")
    implementation("org.apache.hudi:hudi-hadoop-mr:1.0.2")

    // ============ Immutables ============
    implementation("org.immutables:value:2.10.1")
    annotationProcessor("org.immutables:value:2.10.1")

    // ============ S3 Tables Iceberg ============
    implementation("software.amazon.s3tables:s3-tables-catalog-for-iceberg:0.1.3")

    // ============ LakeSoul ============
    implementation("com.dmetasoul:lakesoul-common:2.6.2")
    implementation("com.dmetasoul:lakesoul-io-java:2.6.2")

    // ============ Test ============
    testImplementation("org.junit.jupiter:junit-jupiter:${versions["junit"]}")
    testImplementation("org.mockito:mockito-core:${versions["mockito"]}")
    testImplementation("org.hamcrest:hamcrest:${versions["hamcrest"]}")
    testImplementation("org.jmockit:jmockit:${versions["jmockit"]}")
}

// ============ Code Generation (disabled - using Maven pre-generated sources) ============
// All code generation is handled by Maven: ANTLR, JFlex, CUP, Protobuf

// ============ Patch SqlParser for Gradle compatibility ============
// The Maven-generated SqlParser.java uses Stack<Symbol> but java-cup-runtime 0.11-a-czt01-cdh
// requires raw Stack. This task patches the file to use raw Stack.
val patchSqlParser by tasks.registering {
    group = "code generation"
    description = "Patch SqlParser.java for java-cup-runtime compatibility"

    val sqlParserFile = file("target/generated-sources/cup/org/apache/doris/analysis/SqlParser.java")

    doLast {
        if (sqlParserFile.exists()) {
            var content = sqlParserFile.readText()

            // Check if already patched
            if (!content.contains("@SuppressWarnings(\"rawtypes\")") ||
                content.contains("java.util.Stack<java_cup.runtime.Symbol> stack,")) {

                // Patch the do_action method signature to use raw Stack
                content = content.replace(
                    """  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack<java_cup.runtime.Symbol> stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP${"$"}SqlParser${"$"}do_action(act_num, parser, stack, top);
  }""",
                    """  /** Invoke a user supplied parse action. */
  @Override
  @SuppressWarnings("rawtypes")
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP${"$"}SqlParser${"$"}do_action(act_num, parser, (java.util.Stack<java_cup.runtime.Symbol>)stack, top);
  }"""
                )

                sqlParserFile.writeText(content)
                println("Patched SqlParser.java for java-cup-runtime compatibility")
            } else {
                println("SqlParser.java already patched")
            }
        }
    }
}

// ============ Task Dependencies ============
tasks.compileJava {
    dependsOn(patchSqlParser)

    options.isIncremental = true
    options.isFork = true
    options.forkOptions.memoryMaximumSize = "4g"
}

// ============ JAR Configuration ============
tasks.jar {
    archiveBaseName.set("doris-fe")

    manifest {
        attributes("Main-Class" to "org.apache.doris.DorisFE")
    }

    // Copy dependencies to lib folder instead of fat jar
    doLast {
        copy {
            from(configurations.runtimeClasspath)
            into("$buildDir/libs/lib")
        }
    }
}

// ============ Clean ============
tasks.clean {
    delete("target/generated-sources")
}

// ============ Test Configuration ============
sourceSets {
    test {
        java {
            srcDirs("src/test/java")
        }
        resources {
            srcDirs("src/test/resources")
        }
    }
}

tasks.test {
    useJUnitPlatform()

    // Parallelism: use FE_UT_PARALLEL env var or auto-detect
    val parallel = System.getenv("FE_UT_PARALLEL")?.toIntOrNull()
        ?: (Runtime.getRuntime().availableProcessors() / 2).coerceIn(1, 8)
    maxParallelForks = parallel

    // JVM optimization for faster test execution
    jvmArgs(
        "-Xmx4g",
        "-XX:+UseParallelGC",
        "-XX:TieredStopAtLevel=1",
        "-Djava.awt.headless=true"
    )

    // Incremental test execution
    outputs.upToDateWhen { false }  // Always run tests when explicitly requested

    // Test logging
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = false
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }

    // Fail fast for faster feedback
    failFast = true

    // Report directory
    reports {
        html.required.set(true)
        junitXml.required.set(true)
    }

    doFirst {
        println("Running tests with $maxParallelForks parallel forks")
    }
}

// ============ Fast compile task ============
tasks.register("fastCompile") {
    group = "build"
    description = "Fast incremental compilation (skips code generation if unchanged)"
    dependsOn(tasks.compileJava)
}
